language: rust

cache:
  directories:
    - $HOME/.cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
    - env: CARGO-TRAVIS
  fast_finish: true
  include:
    - rust: stable
      env: RUSTFMT
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check
    - rust: stable
      env: CLIPPY
      install:
        - rustup component add clippy
      script:
        - cargo clippy -- -D clippy

services:
  - docker

before_install:
  - docker run -d -p 127.0.0.1:8080:8080 mockersf/jenkins-api-rs-tests
  - sleep 10
