language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

services:
  - docker

before_install:
- docker run -d -p 127.0.0.1:8080:8080 mockersf/jenkins-api-rs-tests
- sleep 10
