language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
  - rust: stable
    env: RUSTFMT
    install:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt -- --write-mode=diff
  - rust: nightly
    env: CLIPPY
    install:
    - travis_wait cargo install clippy || echo "clippy already installed"
    script:
    - cargo clippy -- -D clippy

services:
  - docker

before_install:
- docker run -d -p 127.0.0.1:8080:8080 mockersf/jenkins-api-rs-tests
- sleep 10
