language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
  - rust: stable
    env: RUSTFMT
    install:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt -- --write-mode=diff
  - rust: nightly
    env: CLIPPY
    install:
    - travis_wait cargo install clippy || echo "clippy already installed"
    script:
    - cargo clippy -- -D clippy

services:
  - docker

before_install:
- docker run -d -p 127.0.0.1:8080:8080 mockersf/jenkins-api-rs-tests
- sleep 10

# Upload docs
after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then
      cargo doc --no-deps &&
      echo "<meta http-equiv=refresh content=0;url=os_balloon/index.html>" > target/doc/index.html &&
      git clone https://github.com/davisp/ghp-import.git &&
      ./ghp-import/ghp_import.py -n -p -f -m "Documentation upload" -r https://"$GH_TOKEN"@github.com/"$TRAVIS_REPO_SLUG.git" target/doc &&
      echo "Uploaded documentation"
    fi
