[package]
name = "jenkins_api"
version = "0.2.0"
authors = ["François Mockers <mockersf@gmail.com>"]
description = "Bindings for the Jenkins JSON API"
repository = "https://github.com/mockersf/jenkins-api.rs"
homepage = "https://github.com/mockersf/jenkins-api.rs"
documentation = "https://docs.rs/jenkins_api"
keywords = ["jenkins"]
license = "MIT"
readme = "README.md"

[badges]
travis-ci = { repository = "mockersf/jenkins-api.rs" }

[dependencies]
reqwest = "0.8"
hyper = "0.11"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

urlencoding = "1.0.0"

failure = "0.1"
